
import { yekan } from '@/utils/font'
import './globals.css'
import Layout from '@/layout/Layout'
import NextAuthProvider from 'src/provider/NextAuthProvider'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
 
  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className}>
        <NextAuthProvider>
      <Layout>{children}</Layout>
        </NextAuthProvider>
      </body>
    </html>
  )
}
